# Generated by Django 4.0.4 on 2022-06-16 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_post_content_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clase',
            new_name='Proceso',
        ),
        migrations.RemoveField(
            model_name='reglamento',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['-created'], 'verbose_name': 'proceso', 'verbose_name_plural': 'procesos'},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reglamento',
        ),
    ]
